[gcp_credentials]
account = ""
client_id = "764086051850-6qr4p6gpi6hn506pt8ejuq83di341hur.apps.googleuserco$"
client_secret = "d-FL95Q19q7MQmFpd7hHD0Ty"
quota_project_id = "healthy-dragon-300820"
refresh_token = "1//053cx1lx-pruTCgYIARAAGAUSNwF-L9Ir_0TYh7HFDdwRNnV6S1tJsGZ$",
type = "authorized_user"
universe_domain = "googleapis.com"